import { FSIWeightClasses } from "@nsholmes/combat-stats-types/bracket.model";

export const WeightClasses: FSIWeightClasses[] = [
  {
    age_class_id: 725,
    create_date: "09/01/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 989,
    max: 50.0,
    min: 40.1,
    name: "Light Atomweight 40 (40.1 - 50.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "09/01/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 990,
    max: 60.0,
    min: 50.1,
    name: "Light Atomweight 50 (50.1 - 60.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "09/01/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 991,
    max: 70.0,
    min: 60.1,
    name: "Light Atomweight 60 (60.1 - 70.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "09/01/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 992,
    max: 80.0,
    min: 70.1,
    name: "Light Atomweight 70 (70.1 - 80.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 859,
    max: 90.0,
    min: 80.1,
    name: "Atomweight (80.1 - 90.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 860,
    max: 100.0,
    min: 90.1,
    name: "Flyweight (90.1 - 100.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 861,
    max: 110.0,
    min: 100.1,
    name: "Bantamweight (100.1 - 110.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 862,
    max: 120.0,
    min: 110.1,
    name: "Featherweight (110.1 - 120.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 863,
    max: 130.0,
    min: 120.1,
    name: "Lightweight (120.1 - 130.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 864,
    max: 140.0,
    min: 130.1,
    name: "Light Welterweight (130.1 - 140.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 865,
    max: 150.0,
    min: 140.1,
    name: "Welterweight (140.1 - 150.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 866,
    max: 160.0,
    min: 150.1,
    name: "Light Middleweight (150.1 - 160.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 867,
    max: 170.0,
    min: 160.1,
    name: "Middleweight (160.1 - 170.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 868,
    max: 180.0,
    min: 170.1,
    name: "Light Heavyweight (170.1 - 180.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 869,
    max: 190.0,
    min: 180.1,
    name: "Light Cruiserweight (180.1 - 190.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 870,
    max: 200.0,
    min: 190.1,
    name: "Cruiserweight (190.1 - 200.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 871,
    max: 215.0,
    min: 200.1,
    name: "Super Cruiserweight (200.1 - 215.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 872,
    max: 230.0,
    min: 215.1,
    name: "Heavyweight (215.1 - 230.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
  {
    age_class_id: 725,
    create_date: "03/25/2023",
    deleted_date: "",
    gender: { id: 1, name: "M" },
    id: 873,
    max: 999.0,
    min: 230.1,
    name: "Super Heavyweight (230.1 - 999.0)",
    pro_classification: { id: 1, name: "Amateur" },
    sport: {
      abbreviation: "PS",
      create_date: "03/25/2023",
      gender: { id: 1, name: "M" },
      has_positions: false,
      id: 14,
      name: "Point Sparring",
    },
    units: null,
    units_id: null,
  },
];
